### ISSUE TITLE
Workflows

### ISSUE THREAD

**Issue by kbodwin** [tidymodels/tidyclust#13]
I think the next short-term step is to let these models be part of a `workflow` with a `recipe`.  Right now there's an error from `add_model()`:  "Error: `spec` must be a `model_spec`."

I'm guessing that `cluster_spec` can't (and shouldn't?) be a subclass of `model_spec`, so that would mean that either `add_model()` needs a S3 method for cluster specs, or we need a `add_celery_model()`

**Comment by DavisVaughan** [comment]
Some thoughts:

- workflows has been defined in "stages" to sort of account for this possibility. There is a "fit stage" where you can swap out the thing used to fit. So I think we are going to have a `fit-action-celery.R` file dedicated to celery, like how there is a `fit-action-model.R` file dedicated to parsnip model specs. This allows celery to differ from parsnip when it matters, and we can easily account for those differences in workflows because there is a dedicated code path just for celery.
- `control_workflow()` currently has a `control_parsnip` argument. I think we could rename this to `control` to make it more generic, and allow a `control_celery` object through here too (it would become agnostic to the type of the actual control object and rely on the underlying `fit()` method to check the control object type)
- `add_variables()` requires the `outcomes` argument, but you can do `outcomes = NULL` to say "no outcome". I think that might be the best we can do there
